spring.application.name=labatri
server.port=8080

spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:5432/${DB_NAME:rbpo_db}
spring.datasource.username=${DB_USER:rbpo_user}
spring.datasource.password=${DB_PASSWORD:rbpo_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update  
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

greeting.text=Hello
greeting.int=2302
